---

root: true

plugins:
  - jest

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

env:
  node: true
  es2020: true

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0